config/routes.rb
Rails.application.routes.draw do

  get 'albums/show'

  get 'tours/index'
  get 'tours/show'
  get 'clubs/index'
  get 'clubs/show'
  get 'subjects/index'
  get 'subjects/show'

  mount Ckeditor::Engine => '/ckeditor'
  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :subjects
        resources :directions
        resources :newsbites
        resources :tours
        resources :albums do
          resources :images, :only => [:create, :destroy]
        end
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path

    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :subjects
      resources :directions
      resources :newsbites
      resources :tours
      resources :albums do
        resources :images, :only => [:create, :destroy]
      end
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
################################################################################
# Model:  Album
#
# Purpose:
#
# Album attributes:
#   title             - title:           string,  not NULL
#   content           - content:  text
#   images            - images gallery:  json
#   position          - sorting index:   integer, not NULL
#   status            - status:          enum { active (0) | archived (1) }
#   cover             - cover image:     string
#
#  24.08.2017 ZT
#  27.08.2017   Cover added
################################################################################
class Album < ApplicationRecord
  mount_uploaders :images, ImageUploader
  mount_uploader  :cover,  CoverUploader
  
  before_save     :set_position

  enum status: %w(active archived)

  validates :title, presence: true

  private

    def set_position
      if self.id.blank?
        last_item = Album.order(:position).last
        self.position = last_item.blank? ? 1 : last_item.position.to_i + 1
      end
    end
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  before_action :set_album, only: [:show, :edit, :update,:destroy]
  after_action  :remove_images_dir, only: :destroy

  def index
    @albums = policy_scope(Album)
  end

  def show
    authorize @album
  end

  def new
    @album = Album.new
    authorize @album
  end

  def edit
    authorize @album
  end

  def create
    @album = Album.new(album_params)
    authorize @album
    if @album.save
      flash[:success] = t('messages.created', model: @album.class.model_name.human)
      redirect_to [:admin, @album]
    else      
      render :new
    end
  end

  def update
    authorize @album
    if @album.update(album_params)
      flash[:success] = t('messages.updated', model: @album.class.model_name.human)
      redirect_to [:admin, @album]
    else      
      render :edit
    end
  end

  def destroy
    authorize @album
    @album.destroy
    flash[:success] = t('messages.deleted', model: @album.class.model_name.human)
    redirect_to admin_albums_path
  end

  private

    # Removes upload images directory of a destroyed Gallery
    def remove_images_dir
      if @album.images.present?
        dir = File.dirname(@album.images.first.current_path)
        FileUtils.remove_dir dir if Dir.empty?(dir)
      end
    end
   
    # Uses callbacks to share common setup or constraints between actions
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allows a trusted parameter 'white list' through
    def album_params
      params.require(:album).permit(:title, :content, :images, :position, :status, {images: []}, :cover)
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    puts "SHOW-1: #{params}"
    @album = Album.find(params[:format])
    puts "SHOW-2: #{@album.title}"
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/admin/albums/_form.html.haml
.row
  .col-md-6
    = simple_form_for([:admin, @album], html: {multipart: true}) do |f|
      = f.error_notification message: t('messages.error_notification')

      .form-inputs
        = f.input :title

        .input-group-addon
          = f.input :cover, as: :file
          - if f.object.cover?
            .input-group
              = image_tag @album.cover.thumb.url
              .input-group-addon
                = f.input :remove_cover, as: :boolean

        = f.input :content,  as: :ckeditor, input_html: { ckeditor: { toolbar: 'mini' } }

        .input-group-addon
          = f.input :images,   as: :file, :input_html => { :multiple => true } 

        = f.input :position, as: :hidden

        = f.input :status, default: 1
        /= render 'admin/shared/status_buttons', f: f

      .form_actions
        .row
          .col-md-3
            = f.submit t('actions.save'), class: 'btn btn-primary btn-block'
          .col-md-3
            = link_to t('actions.back'), admin_albums_path, class: 'btn btn-default btn-block'

app/views/admin/albums/edit.html.haml
%h1= "#{t('actions.editing', model: @album.class.model_name.human)}"
= render 'form'

app/views/admin/albums/index.html.haml
%h1= t Album.model_name.human(count: 2)
%table.table.table-hover
  %thead
    %tr
      %th= Album.human_attribute_name(:title)
      /%th= Album.human_attribute_name(:content)
      /%th= Album.human_attribute_name(:images)
      %th= Subject.human_attribute_name(:cover)
      %th= "Количество фото"
      %th= Album.human_attribute_name(:position)
      %th= t 'status.status'
      %th= t 'actions.actions'

  %tbody
    - @albums.each do |album|
      %tr
        %td= album.title
        /%td= album.content
        /%td= album.images
        %td= image_tag album.cover.thumb.url if album.cover?
        %td= album.images.count
        %td= album.position
        %td= status_mark album.status
        %td= render 'admin/shared/index_buttons', resource: album
%br
.row
  .col-md-2
    = link_to t('actions.create'), new_admin_album_path, class: 'btn btn-primary btn-block'

app/views/admin/albums/new.html.haml
%h1= "#{t('actions.new', model: @album.class.model_name.human)}"
= render 'form'

app/views/admin/albums/show.html.haml
%h1= t Album.model_name.human
%table.table.table-striped
  %tbody
    - @album.attributes.each do |key, value|
      - if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at' || key == 'images'
        //skip these attributes
      -else
        %tr
          - if key == 'status'
            %td= t 'status.status'
            %td= status_mark @album.status
          - elsif key == 'cover'
            %td= t 'cover'
            %td= image_tag @album.cover.thumb.url if @album.cover?
          -else
            %td= t "activerecord.attributes.album.#{key}"
            %td= value

- if @album.images.present?
  .input-group-addon
    %h3= "Images Collection"
    %table.table.table-striped
      - @album.images.each_with_index do |image, index|   #grab the index
        %tr
          %td= image_tag(image.thumb.url)
          %td= link_to "Delete", admin_album_image_path(@album, index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" }

  .input-group-addon
    = form_for @album, url: admin_album_images_path(@album), method: :post do |f| # use customized url endpoint 
      .row
        .col-sm-2
          = f.file_field :images, multiple: true
        .col-sm-2
        = f.submit "Add More Images"

.form_actions
  .row
    .col-sm-2
      = link_to t('actions.back'), admin_albums_path, class: 'btn btn-primary btn-block'