config/routes.rb
Rails.application.routes.draw do

  get 'albums/show'

  get 'tours/index'
  get 'tours/show'
  get 'clubs/index'
  get 'clubs/show'
  get 'subjects/index'
  get 'subjects/show'

  mount Ckeditor::Engine => '/ckeditor'
  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :subjects
        resources :directions
        resources :newsbites
        resources :tours
        resources :albums do
          resources :images, :only => [:create, :destroy]
        end
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path

    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :subjects
      resources :directions
      resources :newsbites
      resources :tours
      resources :albums do
        resources :images, :only => [:create, :destroy]
      end
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
################################################################################
# Model:  Tour
#
# Purpose:
#
# Tour attributes:
#   title       - title:              string,  not NULL
#   start_date  - Tour's start_date : date,    not NULL
#   finish_date - Tour's finish_date: date,    not NULL
#   content     - content:            text,    not NULL
#   cover       - cover:              string
#   status      - status:             enum { active (0) | archived (1) }
#
#  24.08.2017 ZT
################################################################################
class Tour < ApplicationRecord
  mount_uploader :cover, CoverUploader
  
  enum status: %w(active archived)

  validates :title,       presence: true
  validates :start_date,  presence: true
  validates :finish_date, presence: true
  validates :content,     presence: true
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::BaseController
  before_action :set_tour, only: [:show, :edit, :update,:destroy]
  after_action  :remove_cover_dir, only: :destroy

  def index
    @tours = policy_scope(Tour)
  end

  def show
    authorize @tour
  end

  def new
    @tour = Tour.new
    authorize @tour
  end

  def edit
    authorize @tour
  end

  def create
    @tour = Tour.new(tour_params)
    authorize @tour
    if @tour.save
      flash[:success] = t('messages.created', model: @tour.class.model_name.human)
      redirect_to [:admin, @tour]
    else      
      render :new
    end
  end

  def update
    authorize @tour
    if @tour.update(tour_params)
      flash[:success] = t('messages.updated', model: @tour.class.model_name.human)
      redirect_to [:admin, @tour]
    else      
      render :edit
    end
  end

  def destroy
    authorize @tour
    @tour.destroy
    flash[:success] = t('messages.deleted', model: @tour.class.model_name.human)
    redirect_to admin_tours_path
  end

  private
    # Removes upload cover directory of a destroyed Account
    def remove_cover_dir
      dir =  "public/uploads/subject/cover/#{@subject.id}"
      FileUtils.remove_dir dir if Dir.empty?(dir)
    end

    # Uses callbacks to share common setup or constraints between actions
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Only allows a trusted parameter 'white list' through
    def tour_params
      params.require(:tour).permit(:title, :start_date, :finish_date, :content, :cover, :status, :remove_cover)
    end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @tours = Tour.active
  end

  def show
    @tour = Tour.find(params[:id])
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/admin/tours/_form.html.haml
.row
  .col-md-6
    = simple_form_for([:admin, @tour], html: {multipart: true}) do |f|
      = f.error_notification message: t('messages.error_notification')

      .form-inputs
        = f.input :title
        = f.input :start_date
        = f.input :finish_date
        = f.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'mini' } }

        .input-group-addon
          = f.input :cover, as: :file
          - if f.object.cover?
            .input-group
              = image_tag f.object.cover.thumb.url
              .input-group-addon
                = f.input :remove_cover, as: :boolean

        = f.input :status, default: 1
        /= render 'admin/shared/status_buttons', f: f

      .form_actions
        .row
          .col-md-3
            = f.submit t('actions.save'), class: 'btn btn-primary btn-block'
          .col-md-3
            = link_to t('actions.back'), admin_tours_path, class: 'btn btn-default btn-block'

app/views/admin/tours/edit.html.haml
%h1= "#{t('actions.editing', model: @tour.class.model_name.human)}"
= render 'form'

app/views/admin/tours/index.html.haml
%h1= t Tour.model_name.human(count: 2)
%table.table.table-hover
  %thead
    %tr
      %th= Tour.human_attribute_name(:title)
      %th= Tour.human_attribute_name(:start_date)
      %th= Tour.human_attribute_name(:finish_date)
      /%th= Tour.human_attribute_name(:content)
      %th= Tour.human_attribute_name(:cover)
      %th= t 'status.status'
      %th= t 'actions.actions'

  %tbody
    - @tours.each do |tour|
      %tr
        %td= tour.title
        %td= tour.start_date
        %td= tour.finish_date
        /%td= tour.content
        %td= image_tag tour.cover.thumb.url if tour.cover?
        %td= status_mark tour.status
        %td= render 'admin/shared/index_buttons', resource: tour
%br
.row
  .col-md-2
    = link_to t('actions.create'), new_admin_tour_path, class: 'btn btn-primary btn-block'

app/views/admin/tours/new.html.haml
%h1= "#{t('actions.new', model: @tour.class.model_name.human)}"
= render 'form'

app/views/admin/tours/show.html.haml
%h1= t Tour.model_name.human
%table.table.table-striped
  %tbody
    - @tour.attributes.each do |key, value|
      - if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at'
        //skip these attributes
      -else
        %tr
          - if key == 'status'
            %td= t 'status.status'
            %td= status_mark @tour.status
          - elsif key == 'cover'
            %td= t 'cover'
            %td= image_tag @tour.cover.thumb.url if @tour.cover?
          -else
            %td= t "activerecord.attributes.tour.#{key}"
            %td= value

.form_actions
  .row
    .col-md-2
      = link_to t('actions.back'), admin_tours_path, class: 'btn btn-primary btn-block'