config/routes.rb
Rails.application.routes.draw do

  get 'albums/show'

  get 'tours/index'
  get 'tours/show'
  get 'clubs/index'
  get 'clubs/show'
  get 'subjects/index'
  get 'subjects/show'

  mount Ckeditor::Engine => '/ckeditor'
  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :subjects
        resources :directions
        resources :newsbites
        resources :tours
        resources :albums do
          resources :images, :only => [:create, :destroy]
        end
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path

    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :subjects
      resources :directions
      resources :newsbites
      resources :tours
      resources :albums do
        resources :images, :only => [:create, :destroy]
      end
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_carousel.html.erb
<div class="col-md-12 text-center"><h2>Наши фотоальбомы</h2></div>
<div class="container">
  <div class="col-md-12" >
    <div class="carousel slide col-md-11" data-ride="carousel" id="myCarousel">
      <div class="carousel-inner">
        <div class="col-md-2"></div>
        <% images.each_with_index do |value, index| %>
          <% if index == 0 %>
            <div class="item active">
              <div class="col-lg-3 col-xs-3 col-md-3 col-sm-3">
                <%= link_to image_tag(value.model.cover.view.url, :class => "img-responsive") + "#{value.model.title}", "#" %> <!-- value.model.title, :class => "img-responsive"-->
              </div>
            </div>
          <% else %>
            <div class="item">
              <div class="col-lg-3 col-xs-3 col-md-3 col-sm-3">
                <%= link_to image_tag(value.model.cover.view.url,:class => "img-responsive") + "#{value.model.title}", "#" %>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="col-md-1"></div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    carousel_multi_items();
  });
</script>

app/views/shared/_carousel_images.html.haml
#myCarousel.carousel.slide.carousel-fade{"data-ride" => "carousel", "data-interval" => "4000"}
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    - for i in 1..images.count-1
      %li{"data-slide-to" => "i", "data-target" => "#myCarousel"}

  / Wrapper for slides
  .carousel-inner{:role => "listbox"}
    - images.each_with_index do |value, index|
      - if index == 0
        .item.active
          = link_to image_tag(value.model.cover.view.url, :class => "center-block"), albums_show_path(value.model.id)
          .carousel-caption
            %h3= value.model.title
      - else
        .item
          = link_to image_tag(value.model.cover.view.url, :class => "center-block"), albums_show_path(value.model.id)
          .carousel-caption
            %h3= value.model.title
  
  / Left and right controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only= t :previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only= t :next
%br
%br

app/views/shared/_debug.html.haml
= debug params

- unless @current_user.nil?
  = debug "current_user: #{@current_user.full_name}; current_role: #{@current_user.role}"

= debug "Versions: #{RUBY_ENGINE}-#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL} | Rails: #{Rails.version}"

- if GIT_BRANCH.present?
  = debug "Git branch: #{GIT_BRANCH}; Commit: #{GIT_COMMIT} (#{l GIT_COMMIT_TIMESTAMP, format: '%d.%m.%Y %H:%M'})"

app/views/shared/_footer.html.haml
%footer
  .container
    %hr
      .row
        .col-sm-offset-1.col-sm-5.vcenter
          = "© Lightman School, 2017"
        .col-sm-3.vcenter
          = image_tag "/ZT_Lab_6.png", size: "32x32"
          = "ZT Lab (разработка сайта)"
        .col-sm-2.vcenter
          = "Илья Кулешов (логотип)"

    = render 'shared/debug' if Rails.env.development? && ZT_DEBUG

app/views/shared/_logo.html.haml
.container
  .row
    .col-sm-3
      =link_to image_tag('lms_logo.jpg', alt: 'Lightman School',  size: '288x162'), url_for(controller: :pages, action: :home)
    .col-sm-7.col-sm-offset-2
      .row.logo-style
        
        .col-sm-12
          %p.lead +38 (093) 149 20 38
        .col-sm-12
          %hp.lead +38 (067) 486 03 69
      

app/views/shared/_shim.html.haml
/[if lt IE 9]
  %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

app/views/shared/_top_navigation.html.erb
<%# Source: http://www.w3schools.com/bootstrap/bootstrap_navbar.asp %>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header"> <!-- Brand and toggle get grouped for better mobile display -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to app_name, root_path %>
      </div>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to root_path do %>
            <span class="glyphicon glyphicon-home"></span> <%= t :home %>
          <% end %>
        </li>
        <!--li class="dropdown">
          <%#= link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do %>
            <%= t :about_us  %>
            <span class="caret"></span>
          <%# end %>

          <ul class="dropdown-menu">
            <li><%#= link_to t(:about_company), '#' %></li> 
            <li><%#= link_to t(:contacts),      '#' %></li> 
          </ul>
        </li-->

        <!--li><%= link_to t(:help), '#' %></li-->
        
        <li class="dropdown">
          <%= link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do %>
            <%= t :pages %>
            <span class="caret"></span>
          <% end %>

          <ul class="dropdown-menu">
            <li><%= link_to t(Subject.model_name.human(count: 2)), subjects_index_path %></li>
            <!--li><%#= link_to t(Club.model_name.human(count: 2)),    clubs_index_path %></li>
            <li><%#= link_to t(Tour.model_name.human(count: 2)),    tours_index_path %></li-->
          </ul>
        </li>
      </ul>

      <!-- add search form -->
      <!--div class="col-sm-3 col-sm-3">
        <form class="navbar-form" role="search">
          <div class="input-group">
            <input class="form-control" placeholder="<%= t(:search) %>" name="q" type="text">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </div>
          </div>
        </form>
      </div-->

      <ul class="nav navbar-nav navbar-right">
        <% if MULTILINGUAL %>
          <li class="dropdown">
            <%= link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do %>
              <%= t :language %>
              <span class="caret"></span>
            <% end %>
            <%= language_switch_bootstrap('front') %>
        <% end %>

        <!--li class="dropdown">
          <%= link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do %>
            <%= t :account %>
            <span class="caret"></span>
          <% end %>

          <ul class="dropdown-menu">
            <li>
              <%= link_to '#' do %>
                <span class="glyphicon glyphicon-user"></span>
                <%= t :sign_up  %>
              <% end %>
            </li>
            <li>
              <%= link_to '#' do %>
                <span class="glyphicon glyphicon-log-in"></span>
                <%= t :sign_in  %>
              <% end %>
            </li>
          </ul>
        </li-->
      </ul>
    </div>    <!-- / collapse -->
  </div>      <!-- / container-fluid -->
</nav>

app/views/shared/zt_carousel.html.haml
%h2.col-sm-12.text-center Наши фотоальбомы
.col-sm-6.col-sm-offset-3
  #myCarousel.carousel.slide{"data-interval" => "3000", "data-ride" => "carousel", "data-type" => "multi"}
    .carousel-inner
      - images.each_with_index do |value, index|
        - if index == 0
          .item.active
            /= image_tag(value.model.images.first.preview.url, title: value.model.title, class: 'center-block')
            = image_tag(value.model.cover.view.url, title: value.model.title, class: 'col-sm-3 img-responsive')
            /= value.inspect
            -#.carousel-caption
              %h3= value.model.title
        - else
          .item
            = image_tag(value.model.cover.view.url, title: value.model.title, class: 'col-sm-3  img-responsive')
            /= value.inspect
            -#.carousel-caption
              %h3= value.model.title

    %a.left.carousel-control{"data-slide" => "prev",  :href => "#myCarousel"}
      %i.glyphicon.glyphicon-chevron-left
    %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
      %i.glyphicon.glyphicon-chevron-right
    %br
    %br
:javascript
  $(document).ready(function(){
    carousel_multi_items();
    //$("#myCarousel").carousel();
  });