config/routes.rb
Rails.application.routes.draw do

  get 'albums/show'

  get 'tours/index'
  get 'tours/show'
  get 'clubs/index'
  get 'clubs/show'
  get 'subjects/index'
  get 'subjects/show'

  mount Ckeditor::Engine => '/ckeditor'
  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :subjects
        resources :directions
        resources :newsbites
        resources :tours
        resources :albums do
          resources :images, :only => [:create, :destroy]
        end
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path

    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :subjects
      resources :directions
      resources :newsbites
      resources :tours
      resources :albums do
        resources :images, :only => [:create, :destroy]
      end
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/direction.rb
################################################################################
# Model:  Direction
#
# Purpose: Directions of activity
#
# Direction attributes:
#   name              - name:           string,  not NULL, unique
#   title             - title:          string,  not NULL
#   cover             - cover picture:  string
#   position          - sorting index:  integer, not NULL
#   status            - status:         enum { active (0) | archived (1) }
#
#  22.08.2017 ZT
################################################################################
class Direction < ApplicationRecord
  mount_uploader :cover, CoverUploader
  
  before_save :set_position

  enum status: %w(active archived)

  validates :name,  presence: true, uniqueness: true
  validates :title, presence: true

  private

    def set_position
      if self.id.blank?
        last_item = Direction.order(:position).last
        self.position = last_item.blank? ? 1 : last_item.position.to_i + 1
      end
    end
end

app/controllers/admin/directions_controller.rb
class Admin::DirectionsController < Admin::BaseController
  before_action :set_direction, only: [:show, :edit, :update,:destroy]

  def index
    @directions = policy_scope(Direction)
  end

  def show
    authorize @direction
  end

  def new
    @direction = Direction.new
    authorize @direction
  end

  def edit
    authorize @direction
  end

  def create
    @direction = Direction.new(direction_params)
    authorize @direction
    if @direction.save
      flash[:success] = t('messages.created', model: @direction.class.model_name.human)
      redirect_to [:admin, @direction]
    else      
      render :new
    end
  end

  def update
    authorize @direction
    if @direction.update(direction_params)
      flash[:success] = t('messages.updated', model: @direction.class.model_name.human)
      redirect_to [:admin, @direction]
    else      
      render :edit
    end
  end

  def destroy
    authorize @direction
    @direction.destroy
    flash[:success] = t('messages.deleted', model: @direction.class.model_name.human)
    redirect_to admin_directions_path
  end

  private

    # Uses callbacks to share common setup or constraints between actions
    def set_direction
      @direction = Direction.find(params[:id])
    end

    # Only allows a trusted parameter 'white list' through
    def direction_params
      params.require(:direction).permit(:name, :title, :cover, :position, :status)
    end
end

app/views/admin/directions/_form.html.haml
.row
  .col-md-6
    = simple_form_for([:admin, @direction], html: {multipart: true}) do |f|
      = f.error_notification message: t('messages.error_notification')

      .form-inputs
        = f.input :name
        = f.input :title
        = f.input :cover
        = f.input :position, as: :hidden

        = f.input :status, default: 1
        /= render 'admin/shared/status_buttons', f: f

      .form_actions
        .row
          .col-md-3
            = f.submit t('actions.save'), class: 'btn btn-primary btn-block'
          .col-md-3
            = link_to t('actions.back'), admin_directions_path, class: 'btn btn-default btn-block'

app/views/admin/directions/edit.html.haml
%h1= "#{t('actions.editing', model: @direction.class.model_name.human)}"
= render 'form'

app/views/admin/directions/index.html.haml
%h1= t Direction.model_name.human(count: 2)
%table.table.table-hover
  %thead
    %tr
      %th= Direction.human_attribute_name(:name)
      %th= Direction.human_attribute_name(:title)
      %th= Direction.human_attribute_name(:cover)
      %th= Direction.human_attribute_name(:position)
      %th= t 'status.status'
      %th= t 'actions.actions'

  %tbody
    - @directions.each do |direction|
      %tr
        %td= direction.name
        %td= direction.title
        %td= image_tag direction.cover.thumb.url if direction.cover?
        %td= direction.position
        %td= status_mark direction.status
        %td= render 'admin/shared/index_buttons', resource: direction
%br
.row
  .col-sm-2
    = link_to t('actions.create'), new_admin_direction_path, class: 'btn btn-primary btn-block'

app/views/admin/directions/new.html.haml
%h1= "#{t('actions.new', model: @direction.class.model_name.human)}"
= render 'form'

app/views/admin/directions/show.html.haml
%h1= t Direction.model_name.human
%table.table.table-striped
  %tbody
    - @direction.attributes.each do |key, value|
      - if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at'
        //skip these attributes
      -else
        %tr
          - if key == 'status'
            %td= t 'status.status'
            %td= status_mark @direction.status
          -else
            %td= t "activerecord.attributes.direction.#{key}"
            %td= value

.form_actions
  .row
    .col-md-2
      = link_to t('actions.back'), admin_directions_path, class: 'btn btn-primary btn-block'